server:
  error:
    include-stacktrace: on-param

spring:
   datasource:
      url: jdbc:mysql://localhost:3306/desafio?createDatabaseIfNotExist=true
      username: root
      password: root
   jpa:
      hibernate:
         ddl-auto: update
         
rabbitmq:
   queue:
      name: resultado
   exchange:
      name: amq.direct
   routing:
      key: routing

logging:
   level:
      org:
         hibernate:
            SQL: DEBUG